 # Change these first
owner: bitnulleins # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: bit01
    url: https://www.bit01.de
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
  - name: bytethinks
    url: https://www.bytethinks.de
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
  - name: Keikogi Tool
    url: https://keikogi.bitnulleins.de
  - name: Bricksfinder
    url: https://bricksfinder.bit01.de
    expectedStatusCodes:
      - 200
  - name: Dohrn Heizung
    url: https://www.dohrn-heizung.de
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
  - name: Spielgruppe Halstenbek
    url: https://www.spielgruppe-halstenbek.de
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
  - name: Forschungsgruppe
    url: https://datascience.entavis.com
    __dangerous__body_down: "There has been a critical error on this website"
    maxResponseTime: 5000
  - name: Augenarzt Tornesch
    url: https://www.augenarzt-tornesch.de
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
  - name: Zahnarzt Tornesch
    url: https://www.zahnarzt-richel.de
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
  - name: SYNOLOGY
    url: $SECRET_SITE

workflowSchedule:
  uptime: "*/60 * * * *"

status-website:
  baseUrl: /monitoring
  logoUrl: https://raw.githubusercontent.com/bitnulleins/monitoring/refs/heads/master/assets/monitoring.svg
  name: bitnulleins
  introTitle: "**Website status**"
  introMessage: "This page provides an overview of the status of the websites I maintain:"
  themeUrl: https://bitnulleins.github.io/monitoring/custom.css
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Config:
# See https://upptime.js.org/docs/configuration
