 # Change these first
owner: bitnulleins # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: bit01
    url: https://www.bit01.de
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
    maxResponseTime: 2000
  - name: bytethinks
    url: https://www.bytethinks.de
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
    maxResponseTime: 2000
  - name: Keikogi Tool
    url: https://keikogi.bitnulleins.de
    maxResponseTime: 2000
  - name: Bricksfinder
    url: https://bricksfinder.bitnulleins.de
    expectedStatusCodes:
      - 200
    maxResponseTime: 2000
  - name: Handwerker
    url: $SITE_HANDWERKER
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
    maxResponseTime: 2000
  - name: Spielgruppe
    url: $SITE_SPIELGRUPPE
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
    maxResponseTime: 2000
  - name: Karate
    url: $SITE_KARATE
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
    maxResponseTime: 2000
  - name: Forschungsgruppe
    url: $SITE_FORSCHUNG
    __dangerous__body_down: "There has been a critical error on this website"
    maxResponseTime: 2000
  - name: Auge
    url: $SITE_AUGE
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
    maxResponseTime: 2000
  - name: Zahn
    url: $SITE_ZAHN
    __dangerous__body_down: "Es gab einen kritischen Fehler auf deiner Webseite"
    maxResponseTime: 2000
  - name: SYNOLOGY
    url: $SITE_SYNOLOGY
    maxResponseTime: 4000
    __dangerous__insecure: true

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"

i18n:
  locale: de-DE

status-website:
  baseUrl: /monitoring
  logoUrl: https://raw.githubusercontent.com/bitnulleins/monitoring/refs/heads/master/assets/monitoring.svg
  name: bitnulleins
  introTitle: "**Website status**"
  introMessage: "This page provides an overview of the status of my supervised projects:"
  themeUrl: https://bitnulleins.github.io/monitoring/custom.css
  robotsText: "User-agent: * \n Disallow: /"
  favicon: https://bitnulleins.de/favicon-32x32.png
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
